<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>xarm_scripts</name>
  <version>0.0.0</version>
  <description>Python scripts for xArm robot testing and utilities</description>
  <maintainer email="vinman.cub@gmail.com">Vinman</maintainer>
  <license>BSD</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>uf_ros_lib</exec_depend>
  <exec_depend>xarm_moveit_config</exec_depend>
  <exec_depend>moveit</exec_depend>
  <exec_depend>pymoveit2</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>moveit_hybrid_planning</exec_depend>
  <exec_depend>xarm_hybrid_planning</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

